# URL de connexion à la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce

# Vos identifiants PostgreSQL (à adapter selon votre installation)
spring.datasource.username=postgres
spring.datasource.password=sofyan2004

# Configuration Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true